---
title: "Salary and Income Report"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(knitr)
source("scripts/summary_info.R")
source("scripts/aggregate_tbl.R")
source("scripts/bar_chart.R")
source("scripts/line_plot.R")
source("scripts/pie_chart.R")
```
***
## Introduction

This report is compiled using data collected by the US Census, through their American Community Survey. This is a national survey that samples approximately 3.54 million addresses each year, and collects data on social, economic, housing, and demographic characteristics of Americans. This report aims to explore the wage trends and provide insight into the income characteristics of Washington State and its counties.

***
#### Summary Information
The dataset used for this report consists of `r info_list$row_num` rows and `r info_list$col_num` columns. It separates income by `r info_list$years_num` different years and `r info_list$race_num` different races. There were `r info_list$county_num` counties surveyed.

***
## Sample of Dataset

`r kable(head(get_race_aggregate(df_location), n = 25L), col.names = c("County", "Race", "Average Household Income", "Total County Income"))`
*Sample dataset used since original table contained over 150 rows

- This dataset is ordered showing the counties with the highest median earnings first, with each race in those counties arranged in descending order in terms of average household income

- For the three counties shown in the sample, those that were surveyed as Asian had the highest median income within each county with White Non-Hispanics following close behind

- The order of highest to lowest earners in terms of race stays consistent for the top 4 earning races in the counties shown

***
## Visualizations

`r get_bar_chart(get_race_aggregate(df_location))`
- This chart was intended to show the relationship between the top 3 earners in terms of race for each county.  
  
- We can observe that Asians are the highest earners for most counties, with White Non-Hispanics becoming the lead earners in the lower earning counties. It is also worth observing that Mason County, WA earns considerably less than all the other counties surveyed.

***
`r get_line_plot(get_year_aggregate(df_location))`
- This chart was intended to show the relationship between average household income totals year-over-year.

- We can observe that although Asians were the highest earners for the top earning counties in the previous visualizations, White Non-Hispanics and Whites had the highest income for each year other than 2014.  
Furthermore, those that identified as two or more races displayed the highest wage growth from 2013 to 2018 out of all the races surveyed.

***
`r get_pie_chart(get_state_aggregate(df_location))`
- This chart was intended to show the total income by race in Washington State for 2018. The labels are arranged from highest earners to lowest.

- We can observe that White Non-Hispanics, Whites, those that identify as two or more races, and Asians collectively earned about 50% of Washington's income in 2018. 